#!/usr/bin/env bash
# @file scripts/validate-apm.sh
# @brief Validate APM reproducibility for one or both contexts in temp homes.
# @description
#   Materializes ~/.apm via chezmoi (manifest + committed lockfile), then runs
#   `apm install --global --frozen` in an isolated temp home. A non-zero exit
#   from `--frozen` means the lockfile is missing, stale, or a ref is
#   unresolvable — the only signals that matter for reproducibility.
#   `all` runs both contexts and aggregates results.
# @arg $1 string Context: personal, work, or all (default all).

set -Eeuo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/apm-lib.sh
source "$repo/scripts/apm-lib.sh"

arg="${1:-all}"
case "$arg" in
personal | work) contexts=("$arg") ;;
all) contexts=(personal work) ;;
*)
  printf 'Unsupported context: %s (use personal, work, or all)\n' "$arg" >&2
  exit 1
  ;;
esac

apm_lib_resolve_bins

tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

# @description Run the frozen install gate for one context.
# @description
#   Called as an `if` condition, so set -e errexit is suspended here. Capture
#   install_rc explicitly so a failing `apm install --frozen` is not masked.
#   `--frozen` already enforces lockfile-exists and ref-consistency; a separate
#   `apm audit --ci` call is not needed and introduces false failures when the
#   lockfile lacks a deployed_files section (generated by `apm lock`, not install).
# @arg $1 string Context.
function validate_context() {
  local context="$1" tmp_home="$tmp_root/home-$1" install_rc
  mkdir -p "$tmp_home"
  if ! apm_lib_materialize "$context" "$tmp_root" "$tmp_home" "$repo"; then
    return 1
  fi

  # Run apm from inside the materialized ~/.apm (matches the runtime installer in
  # lib/install/apm.sh) so it operates on the global manifest and lockfile rather
  # than treating the current repo as a local project. Subshell keeps the loop cwd.
  (
    cd "$tmp_home/.apm" &&
      HOME="$tmp_home" \
        XDG_CACHE_HOME="$tmp_home/.cache" XDG_CONFIG_HOME="$tmp_home/.config" XDG_STATE_HOME="$tmp_home/.local/state" \
        "${APM_BIN}" install --global --frozen --parallel-downloads 0
  )
  install_rc=$?

  return "$install_rc"
}

rc=0
for context in "${contexts[@]}"; do
  if validate_context "$context"; then
    printf '%s: PASS\n' "$context"
  else
    printf '%s: FAIL\n' "$context"
    rc=1
  fi
done
exit "$rc"
